
INSERT INTO products (id, description, intervention_type, article) VALUES
(1, 'Tatuaje de Rosa','tattoo', 'https://tattoo-ideas.com/wp-content/uploads/2023/08/pretty-rose-tattoo.jpg'),
(2, 'Piercing de Nariz','piercing', 'https://informacionimagenes.net/wp-content/uploads/2017/07/Piercing-en-nariz-26.jpg'),
(3, 'Tatuaje de Dragón','tattoo', 'https://beautymag.com/wp-content/uploads/2020/12/Traditional-Red-Chinese-Dragon-Tattoo.jpg'),
(4, 'Piercing de Ceja','piercing', 'https://static.diariofemenino.com/pictures/fotos/216000/216012-4.jpg'),
(5, 'Tatuaje de Mariposa','tattoo', 'http://www.tatuajesgeniales.com/wp-content/uploads/2017/03/mejores-tatuajes-de-mariposas-para-mujeres-4.jpg'),
(6, 'Piercing de Labio','piercing', 'https://www.tatuantes.com/wp-content/uploads/2020/07/lips.jpg'),
(7, 'Tatuaje Tribal','tattoo', 'https://tattoo-ideas.com/wp-content/uploads/2016/10/the-battle-suit.jpg'),
(8, 'Piercing de Oreja','piercing', 'https://www.infiernotatuajes.com/wp-content/uploads/2019/08/Piercing-Helix.jpg'),
(9, 'Tatuaje de Calavera','tattoo', 'http://www.tatuajestattoo.com/assets/content/tattoo/42/3277.jpeg'),
(10, 'Piercing de Lengua','piercing', 'https://cdn-0.somosmamas.com.ar/wp-content/uploads/2018/11/piercing-lengua-labios-1024x1024.jpg'),
(11, 'Tatuaje de Serpiente','tattoo', 'https://tattoo-ideas.com/wp-content/uploads/2023/08/Snake-side-tattoo.jpg'),
(12, 'Piercing de Ombligo','piercing', 'https://i.pinimg.com/originals/4b/d2/44/4bd244dad771d39c6ee7caaff53e8bbc.jpg'),
(13, 'Tatuaje de Águila','tattoo', 'https://i.pinimg.com/originals/77/6e/2c/776e2c807d22584591d9d69439b8547d.jpg'),
(14, 'Piercing de Septum','piercing', 'https://www.infiernotatuajes.com/wp-content/uploads/2019/08/Septum.jpg'),
(15, 'Tatuaje de Flores','tattoo', 'https://significadodetatuajes.org/wp-content/uploads/2020/11/tatuajes-de-flores.jpg'),
(16, 'Piercing Industrial','piercing', 'https://tatsnrings.com/wp-content/uploads/2018/03/simple-industrial-piercing-2.jpg'),
(17, 'Tatuaje de León','tattoo', 'https://tattoo-ideas.com/wp-content/uploads/2023/08/Mothers-love-lions.jpg'),
(18, 'Piercing Helix','piercing', 'http://upload.wikimedia.org/wikipedia/commons/3/3c/Helix_piercing.jpg'),
(19, 'Tatuaje de Mandala','tattoo', 'https://tatuajes.wiki/wp-content/uploads/tatuaje-mandalas-img_5ded5f9f69e73.jpg'),
(20, 'Piercing Labret','piercing', 'https://www.askideas.com/media/11/Cute-Vertical-Labret-Piercing-Picture.jpg');
